import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import AnimatedBackground from "@/components/AnimatedBackground"
import Header from "@/components/Header"
// Eliminar esta importación no utilizada
// import Footer from "@/components/Footer"
import ClientLoadingProvider from "@/components/ClientLoadingProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Julio Perez Yañez",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AnimatedBackground />
        <ClientLoadingProvider>
          <Header />
          <div className="pt-20">
            {children}
          </div>
        </ClientLoadingProvider>
      </body>
    </html>
  )
}

